/* Данные каталога ShkrobotS.
   Единственное место, где меняется наполнение: добавил объект в items —
   карточка появилась и в каталоге, и в фильтре. Трогать catalog.html не нужно.

   Категория: { id, name }         id — часть адреса: catalog.html#beds
   Позиция:   { cat, name, img }   img — путь к фото; без него карточка
                                   рисуется текстурной заглушкой.        */

const CATALOG_CATEGORIES = [
  { id: 'dining-tables',  name: 'Столы обеденные' },
  { id: 'coffee-tables',  name: 'Столы журнальные' },
  { id: 'computer-desks', name: 'Компьютерные столы' },
  { id: 'table-bases',    name: 'Подстолья лофт' },
  { id: 'beds',           name: 'Кровати лофт' },
  { id: 'cabinets',       name: 'Шкафы лофт' },
  { id: 'wardrobes',      name: 'Гардеробные лофт' },
  { id: 'shelving',       name: 'Стеллажи' },
  { id: 'consoles',       name: 'Консоли' },
  { id: 'tv-units',       name: 'Тумбы под ТВ' },
  { id: 'hallway',        name: 'Прихожие лофт' },
  { id: 'shoe-racks',     name: 'Обувницы' },
  { id: 'kitchens',       name: 'Кухни встроенные' },
  { id: 'bathroom',       name: 'Тумбы под раковину и стиральную машину' },
  { id: 'kids',           name: 'Мебель для детской' },
  { id: 'office',         name: 'Мебель для офиса' },
  { id: 'education',      name: 'Мебель для учебных заведений' },
  { id: 'horeca',         name: 'Мебель для кафе, баров и ресторанов' },
  { id: 'beauty',         name: 'Мебель для салонов красоты' },
  { id: 'retail',         name: 'Торговое оборудование' },
  { id: 'partitions',     name: 'Перегородки и рейки' },
  { id: 'outdoor',        name: 'Уличная мебель' },
  { id: 'glamping',       name: 'Мебель для глэмпинга и баз отдыха' }
];

/* Позиции каталога.
   img   — крупное фото для лайтбокса (до 1600 px)
   thumb — превью для сетки (до 700 px); если не задан, берётся img
   Категории без позиций рисуются текстурными заглушками. */
const CATALOG_ITEMS = [
  // Уличная мебель — снято раньше, отдельными кадрами
  { cat: 'outdoor',        name: 'Комплект для террасы',                              img: 'images/terrace-pool.jpg' },
  { cat: 'outdoor',        name: 'Комплект для беседки',                              img: 'images/gazebo-tent.jpg' },
  { cat: 'outdoor',        name: 'Уличный комплект на заказ',                         img: 'images/terrace-balcony.jpg' },

  // Уличная мебель — партия 2, реальные объекты заказчиков
  { cat: 'outdoor',       name: 'Угловой диван с журнальным столом',                              img: 'images/catalog/outdoor-01.jpg',         thumb: 'images/catalog/thumb/outdoor-01.jpg' },
  { cat: 'outdoor',       name: 'Комплект кресел со столом',                                      img: 'images/catalog/outdoor-02.jpg',         thumb: 'images/catalog/thumb/outdoor-02.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа с угловым диваном',                             img: 'images/catalog/outdoor-03.jpg',         thumb: 'images/catalog/thumb/outdoor-03.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-зона под перголой',                                        img: 'images/catalog/outdoor-04.jpg',         thumb: 'images/catalog/thumb/outdoor-04.jpg' },
  { cat: 'outdoor',       name: 'Модульный лаунж-комплект',                                       img: 'images/catalog/outdoor-05.jpg',         thumb: 'images/catalog/thumb/outdoor-05.jpg' },
  { cat: 'outdoor',       name: 'Диван с шезлонгом',                                              img: 'images/catalog/outdoor-06.jpg',         thumb: 'images/catalog/thumb/outdoor-06.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван для остеклённой веранды',                          img: 'images/catalog/outdoor-07.jpg',         thumb: 'images/catalog/thumb/outdoor-07.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект с видом на воду',                                 img: 'images/catalog/outdoor-08.jpg',         thumb: 'images/catalog/thumb/outdoor-08.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван для террасы',                                      img: 'images/catalog/outdoor-09.jpg',         thumb: 'images/catalog/thumb/outdoor-09.jpg' },
  { cat: 'outdoor',       name: 'Стол со скамьёй из массива',                                     img: 'images/catalog/outdoor-10.jpg',         thumb: 'images/catalog/thumb/outdoor-10.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван с шезлонгом',                                      img: 'images/catalog/outdoor-11.jpg',         thumb: 'images/catalog/thumb/outdoor-11.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван для сада',                                         img: 'images/catalog/outdoor-12.jpg',         thumb: 'images/catalog/thumb/outdoor-12.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа для веранды',                                   img: 'images/catalog/outdoor-13.jpg',         thumb: 'images/catalog/thumb/outdoor-13.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа с креслами',                                    img: 'images/catalog/outdoor-14.jpg',         thumb: 'images/catalog/thumb/outdoor-14.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван с обеденным столом',                               img: 'images/catalog/outdoor-15.jpg',         thumb: 'images/catalog/thumb/outdoor-15.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект под навесом',                                     img: 'images/catalog/outdoor-16.jpg',         thumb: 'images/catalog/thumb/outdoor-16.jpg' },
  { cat: 'outdoor',       name: 'Длинный диван со столом',                                        img: 'images/catalog/outdoor-17.jpg',         thumb: 'images/catalog/thumb/outdoor-17.jpg' },
  { cat: 'outdoor',       name: 'Скамья со столом для веранды',                                   img: 'images/catalog/outdoor-18.jpg',         thumb: 'images/catalog/thumb/outdoor-18.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа со скамьями',                                   img: 'images/catalog/outdoor-19.jpg',         thumb: 'images/catalog/thumb/outdoor-19.jpg' },
  { cat: 'outdoor',       name: 'Стол со скамьями',                                               img: 'images/catalog/outdoor-20.jpg',         thumb: 'images/catalog/thumb/outdoor-20.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван со столом',                                        img: 'images/catalog/outdoor-21.jpg',         thumb: 'images/catalog/thumb/outdoor-21.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект для террасы',                                     img: 'images/catalog/outdoor-22.jpg',         thumb: 'images/catalog/thumb/outdoor-22.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект в светлой отделке',                               img: 'images/catalog/outdoor-23.jpg',         thumb: 'images/catalog/thumb/outdoor-23.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа для террасы',                                   img: 'images/catalog/outdoor-24.jpg',         thumb: 'images/catalog/thumb/outdoor-24.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект с креслами',                                      img: 'images/catalog/outdoor-25.jpg',         thumb: 'images/catalog/thumb/outdoor-25.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект у барбекю',                                       img: 'images/catalog/outdoor-26.jpg',         thumb: 'images/catalog/thumb/outdoor-26.jpg' },
  { cat: 'outdoor',       name: 'Длинная скамья со столом',                                       img: 'images/catalog/outdoor-27.jpg',         thumb: 'images/catalog/thumb/outdoor-27.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван в тёмной отделке',                                 img: 'images/catalog/outdoor-28.jpg',         thumb: 'images/catalog/thumb/outdoor-28.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект для беседки',                                     img: 'images/catalog/outdoor-29.jpg',         thumb: 'images/catalog/thumb/outdoor-29.jpg' },
  { cat: 'outdoor',       name: 'Обеденная группа в беседке',                                     img: 'images/catalog/outdoor-30.jpg',         thumb: 'images/catalog/thumb/outdoor-30.jpg' },
  { cat: 'outdoor',       name: 'Садовый диван с креслами',                                       img: 'images/catalog/outdoor-31.jpg',         thumb: 'images/catalog/thumb/outdoor-31.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван со столиком',                                      img: 'images/catalog/outdoor-32.jpg',         thumb: 'images/catalog/thumb/outdoor-32.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект для веранды',                                     img: 'images/catalog/outdoor-33.jpg',         thumb: 'images/catalog/thumb/outdoor-33.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект на газоне',                                       img: 'images/catalog/outdoor-34.jpg',         thumb: 'images/catalog/thumb/outdoor-34.jpg' },
  { cat: 'outdoor',       name: 'Лаунж-комплект для крыльца',                                     img: 'images/catalog/outdoor-35.jpg',         thumb: 'images/catalog/thumb/outdoor-35.jpg' },
  { cat: 'outdoor',       name: 'Стол со скамьями для крыльца',                                   img: 'images/catalog/outdoor-36.jpg',         thumb: 'images/catalog/thumb/outdoor-36.jpg' },
  { cat: 'outdoor',       name: 'Садовый диван',                                                  img: 'images/catalog/outdoor-37.jpg',         thumb: 'images/catalog/thumb/outdoor-37.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван для веранды сруба',                                img: 'images/catalog/outdoor-38.jpg',         thumb: 'images/catalog/thumb/outdoor-38.jpg' },
  { cat: 'outdoor',       name: 'Угловой диван со скамьёй',                                       img: 'images/catalog/outdoor-39.jpg',         thumb: 'images/catalog/thumb/outdoor-39.jpg' },

  // coffee-tables
  { cat: 'coffee-tables', name: 'Журнальный стол на геометричном подстолье',               img: 'images/catalog/coffee-tables-01.jpg',     thumb: 'images/catalog/thumb/coffee-tables-01.jpg' },

  // wardrobes
  { cat: 'wardrobes',     name: 'Гардеробная вешалка лофт',                                img: 'images/catalog/wardrobes-01.jpg',         thumb: 'images/catalog/thumb/wardrobes-01.jpg' },
  { cat: 'wardrobes',     name: 'Гардеробная зона с полками',                              img: 'images/catalog/wardrobes-02.jpg',         thumb: 'images/catalog/thumb/wardrobes-02.jpg' },

  // tv-units
  { cat: 'tv-units',      name: 'Тумба под ТВ с деревянными полками',                      img: 'images/catalog/tv-units-01.jpg',          thumb: 'images/catalog/thumb/tv-units-01.jpg' },
  { cat: 'tv-units',      name: 'Тумба под ТВ, металл и массив',                           img: 'images/catalog/tv-units-02.jpg',          thumb: 'images/catalog/thumb/tv-units-02.jpg' },

  // shelving
  { cat: 'shelving',      name: 'Стеллаж из металла и массива',                            img: 'images/catalog/shelving-01.jpg',          thumb: 'images/catalog/thumb/shelving-01.jpg' },
  { cat: 'shelving',      name: 'Комплект стеллажей',                                      img: 'images/catalog/shelving-02.jpg',          thumb: 'images/catalog/thumb/shelving-02.jpg' },
  { cat: 'shelving',      name: 'Стеллаж комбинированный',                                 img: 'images/catalog/shelving-03.jpg',          thumb: 'images/catalog/thumb/shelving-03.jpg' },

  // office
  { cat: 'office',        name: 'Рабочий стол на металлокаркасе · Проект Алое Поле',       img: 'images/catalog/office-01.jpg',            thumb: 'images/catalog/thumb/office-01.jpg' },
  { cat: 'office',        name: 'Кабинет руководителя · Проект Алое Поле',                 img: 'images/catalog/office-02.jpg',            thumb: 'images/catalog/thumb/office-02.jpg' },
  { cat: 'office',        name: 'Переговорный стол · Проект Алое Поле',                    img: 'images/catalog/office-03.jpg',            thumb: 'images/catalog/thumb/office-03.jpg' },
  { cat: 'office',        name: 'Открытое пространство · Проект Алое Поле',                img: 'images/catalog/office-04.jpg',            thumb: 'images/catalog/thumb/office-04.jpg' },
  { cat: 'office',        name: 'Переговорная зона · Проект Алое Поле',                    img: 'images/catalog/office-05.jpg',            thumb: 'images/catalog/thumb/office-05.jpg' },
  { cat: 'office',        name: 'Рабочие места · Проект Алое Поле',                        img: 'images/catalog/office-06.jpg',            thumb: 'images/catalog/thumb/office-06.jpg' },
  { cat: 'office',        name: 'Ряд рабочих мест · Проект Алое Поле',                     img: 'images/catalog/office-07.jpg',            thumb: 'images/catalog/thumb/office-07.jpg' },
  { cat: 'office',        name: 'Стол у панорамного окна · Проект Алое Поле',              img: 'images/catalog/office-08.jpg',            thumb: 'images/catalog/thumb/office-08.jpg' },
  { cat: 'office',        name: 'Переговорная за стеклом · Проект Алое Поле',              img: 'images/catalog/office-09.jpg',            thumb: 'images/catalog/thumb/office-09.jpg' },
  { cat: 'office',        name: 'Переговорный стол на 6 мест · Проект Алое Поле',          img: 'images/catalog/office-10.jpg',            thumb: 'images/catalog/thumb/office-10.jpg' },
  { cat: 'office',        name: 'Офис в стекле и дереве · Проект Алое Поле',               img: 'images/catalog/office-11.jpg',            thumb: 'images/catalog/thumb/office-11.jpg' },
  { cat: 'office',        name: 'Рабочее место у окна · Проект Алое Поле',                 img: 'images/catalog/office-12.jpg',            thumb: 'images/catalog/thumb/office-12.jpg' },
  { cat: 'office',        name: 'Стол с металлическим подстольем · Проект ЖК Ньютон',      img: 'images/catalog/office-13.jpg',            thumb: 'images/catalog/thumb/office-13.jpg' },
  { cat: 'office',        name: 'Переговорный стол · Проект ЖК Ньютон',                    img: 'images/catalog/office-14.jpg',            thumb: 'images/catalog/thumb/office-14.jpg' },
  { cat: 'office',        name: 'Зона ресепшн с диваном · Проект ЖК Ньютон',               img: 'images/catalog/office-15.jpg',            thumb: 'images/catalog/thumb/office-15.jpg' },
  { cat: 'office',        name: 'Стол у окна · Проект ЖК Ньютон',                          img: 'images/catalog/office-16.jpg',            thumb: 'images/catalog/thumb/office-16.jpg' },
  { cat: 'office',        name: 'Ресепшн, массив и металл · Проект ЖК Ньютон',             img: 'images/catalog/office-17.jpg',            thumb: 'images/catalog/thumb/office-17.jpg' },
  { cat: 'office',        name: 'Рабочий стол руководителя · Проект ЖК Ньютон',            img: 'images/catalog/office-18.jpg',            thumb: 'images/catalog/thumb/office-18.jpg' },
  { cat: 'office',        name: 'Переговорный стол, вид сверху · Проект ЖК Ньютон',        img: 'images/catalog/office-19.jpg',            thumb: 'images/catalog/thumb/office-19.jpg' },
  { cat: 'office',        name: 'Стол на П-образном каркасе · Проект ЖК Ньютон',           img: 'images/catalog/office-20.jpg',            thumb: 'images/catalog/thumb/office-20.jpg' },
  { cat: 'office',        name: 'Стол с перфорированной царгой · Проект ЖК Ньютон',        img: 'images/catalog/office-21.jpg',            thumb: 'images/catalog/thumb/office-21.jpg' },
  { cat: 'office',        name: 'Стеллаж-перегородка · Проект ЖК Ньютон',                  img: 'images/catalog/office-22.jpg',            thumb: 'images/catalog/thumb/office-22.jpg' },
  { cat: 'office',        name: 'Рабочее место со стеллажом · Проект ЖК Ньютон',           img: 'images/catalog/office-23.jpg',            thumb: 'images/catalog/thumb/office-23.jpg' },
  { cat: 'office',        name: 'Кабинет на два места · Проект ЖК Ньютон',                 img: 'images/catalog/office-24.jpg',            thumb: 'images/catalog/thumb/office-24.jpg' },
  { cat: 'office',        name: 'Рабочая зона · Проект ЖК Ньютон',                         img: 'images/catalog/office-25.jpg',            thumb: 'images/catalog/thumb/office-25.jpg' },
  { cat: 'office',        name: 'Стол с тумбой · Проект ЖК Ньютон',                        img: 'images/catalog/office-26.jpg',            thumb: 'images/catalog/thumb/office-26.jpg' },
  { cat: 'office',        name: 'Переговорный стол, массив · Проект ЖК Ньютон',            img: 'images/catalog/office-27.jpg',            thumb: 'images/catalog/thumb/office-27.jpg' },
  { cat: 'office',        name: 'Рабочий стол, бетон и металл · Проект Яндекс Про',        img: 'images/catalog/office-28.jpg',            thumb: 'images/catalog/thumb/office-28.jpg' },
  { cat: 'office',        name: 'Переговорный стол · Проект Яндекс Про',                   img: 'images/catalog/office-29.jpg',            thumb: 'images/catalog/thumb/office-29.jpg' },
  { cat: 'office',        name: 'Угловой стол с тумбой · Проект Яндекс Про',               img: 'images/catalog/office-30.jpg',            thumb: 'images/catalog/thumb/office-30.jpg' },
  { cat: 'office',        name: 'Угловое рабочее место · Проект Яндекс Про',               img: 'images/catalog/office-31.jpg',            thumb: 'images/catalog/thumb/office-31.jpg' },
  { cat: 'office',        name: 'Два рабочих стола · Проект Яндекс Про',                   img: 'images/catalog/office-32.jpg',            thumb: 'images/catalog/thumb/office-32.jpg' },
  { cat: 'office',        name: 'Угловой стол руководителя · Проект Яндекс Про',           img: 'images/catalog/office-33.jpg',            thumb: 'images/catalog/thumb/office-33.jpg' },
  { cat: 'office',        name: 'Рабочее место у входа · Проект Яндекс Про',               img: 'images/catalog/office-34.jpg',            thumb: 'images/catalog/thumb/office-34.jpg' },
  { cat: 'office',        name: 'Стол с металлической царгой · Проект Яндекс Про',         img: 'images/catalog/office-35.jpg',            thumb: 'images/catalog/thumb/office-35.jpg' },
  { cat: 'office',        name: 'Кабинет руководителя · Проект Яндекс Про',                img: 'images/catalog/office-36.jpg',            thumb: 'images/catalog/thumb/office-36.jpg' },
  { cat: 'office',        name: 'Угловой стол с тумбами · Проект Яндекс Про',              img: 'images/catalog/office-37.jpg',            thumb: 'images/catalog/thumb/office-37.jpg' },
  { cat: 'office',        name: 'Длинный угловой стол · Проект Яндекс Про',                img: 'images/catalog/office-38.jpg',            thumb: 'images/catalog/thumb/office-38.jpg' },
  { cat: 'office',        name: 'Тумба вдоль стены · Проект Яндекс Про',                   img: 'images/catalog/office-39.jpg',            thumb: 'images/catalog/thumb/office-39.jpg' },
  { cat: 'office',        name: 'Стойка ресепшн · Проект Яндекс Про',                      img: 'images/catalog/office-40.jpg',            thumb: 'images/catalog/thumb/office-40.jpg' },
  { cat: 'office',        name: 'Ресепшн, фасад в бетоне · Проект Яндекс Про',             img: 'images/catalog/office-41.jpg',            thumb: 'images/catalog/thumb/office-41.jpg' },

  // coffee-tables
  { cat: 'coffee-tables', name: 'Приставной столик · Проект Яндекс Про',                   img: 'images/catalog/coffee-tables-02.jpg',     thumb: 'images/catalog/thumb/coffee-tables-02.jpg' },
  { cat: 'coffee-tables', name: 'Журнальный стол в зоне отдыха · Проект Яндекс Про',       img: 'images/catalog/coffee-tables-03.jpg',     thumb: 'images/catalog/thumb/coffee-tables-03.jpg' },
  { cat: 'coffee-tables', name: 'Приставной стол у дивана · Проект Яндекс Про',            img: 'images/catalog/coffee-tables-04.jpg',     thumb: 'images/catalog/thumb/coffee-tables-04.jpg' },
  { cat: 'coffee-tables', name: 'Журнальный стол, низкий · Проект Яндекс Про',             img: 'images/catalog/coffee-tables-05.jpg',     thumb: 'images/catalog/thumb/coffee-tables-05.jpg' },
  { cat: 'coffee-tables', name: 'Журнальный стол на тонком каркасе · Проект Яндекс Про',   img: 'images/catalog/coffee-tables-06.jpg',     thumb: 'images/catalog/thumb/coffee-tables-06.jpg' },
  { cat: 'coffee-tables', name: 'Журнальный стол с полкой · Проект Яндекс Про',            img: 'images/catalog/coffee-tables-07.jpg',     thumb: 'images/catalog/thumb/coffee-tables-07.jpg' },

  // partitions
  { cat: 'partitions',    name: 'Перегородка с геометричным рисунком · Проект Яндекс Про', img: 'images/catalog/partitions-01.jpg',        thumb: 'images/catalog/thumb/partitions-01.jpg' },
  { cat: 'partitions',    name: 'Зонирующая перегородка · Проект Яндекс Про',              img: 'images/catalog/partitions-02.jpg',        thumb: 'images/catalog/thumb/partitions-02.jpg' },

  // cabinets
  { cat: 'cabinets',      name: 'Шкаф с фасадами под бетон · Проект Яндекс Про',           img: 'images/catalog/cabinets-01.jpg',          thumb: 'images/catalog/thumb/cabinets-01.jpg' },
  { cat: 'cabinets',      name: 'Шкаф распашной · Проект Яндекс Про',                      img: 'images/catalog/cabinets-02.jpg',          thumb: 'images/catalog/thumb/cabinets-02.jpg' },
  { cat: 'cabinets',      name: 'Шкаф с распашными дверями · Проект Яндекс Про',           img: 'images/catalog/cabinets-03.jpg',          thumb: 'images/catalog/thumb/cabinets-03.jpg' },
  { cat: 'cabinets',      name: 'Шкаф-гардероб · Проект Яндекс Про',                       img: 'images/catalog/cabinets-04.jpg',          thumb: 'images/catalog/thumb/cabinets-04.jpg' },

  // Мебель для кафе, баров и ресторанов — партия 3
  { cat: 'horeca',          name: 'Лестница с ограждением для бара',                          img: 'images/catalog/horeca-01.jpg',      thumb: 'images/catalog/thumb/horeca-01.jpg' },
  { cat: 'horeca',          name: 'Металлическая лестница лофт',                              img: 'images/catalog/horeca-02.jpg',      thumb: 'images/catalog/thumb/horeca-02.jpg' },
  { cat: 'horeca',          name: 'Диванная зона кафе',                                       img: 'images/catalog/horeca-03.jpg',      thumb: 'images/catalog/thumb/horeca-03.jpg' },
  { cat: 'horeca',          name: 'Стол на рифлёном подстолье',                               img: 'images/catalog/horeca-04.jpg',      thumb: 'images/catalog/thumb/horeca-04.jpg' },
  { cat: 'horeca',          name: 'Посадочная зона у окна',                                   img: 'images/catalog/horeca-05.jpg',      thumb: 'images/catalog/thumb/horeca-05.jpg' },
  { cat: 'horeca',          name: 'Мягкая зона с круглыми столами',                           img: 'images/catalog/horeca-06.jpg',      thumb: 'images/catalog/thumb/horeca-06.jpg' },
  { cat: 'horeca',          name: 'Столы для кофейни',                                        img: 'images/catalog/horeca-07.jpg',      thumb: 'images/catalog/thumb/horeca-07.jpg' },
  { cat: 'horeca',          name: 'Диван с приставным столом',                                img: 'images/catalog/horeca-08.jpg',      thumb: 'images/catalog/thumb/horeca-08.jpg' },
  { cat: 'horeca',          name: 'Столик для кофейни',                                       img: 'images/catalog/horeca-09.jpg',      thumb: 'images/catalog/thumb/horeca-09.jpg' },
  { cat: 'horeca',          name: 'Лаунж-зона кафе',                                          img: 'images/catalog/horeca-10.jpg',      thumb: 'images/catalog/thumb/horeca-10.jpg' },
  { cat: 'horeca',          name: 'Барная стойка с подсветкой',                               img: 'images/catalog/horeca-11.jpg',      thumb: 'images/catalog/thumb/horeca-11.jpg' },
  { cat: 'horeca',          name: 'Барная стойка с деревянной столешницей',                   img: 'images/catalog/horeca-12.jpg',      thumb: 'images/catalog/thumb/horeca-12.jpg' },

  // Торговое оборудование — партия 3
  { cat: 'retail',          name: 'Торговый стол для музыкального магазина',                  img: 'images/catalog/retail-01.jpg',      thumb: 'images/catalog/thumb/retail-01.jpg' },
  { cat: 'retail',          name: 'Витринный стол с полкой',                                  img: 'images/catalog/retail-02.jpg',      thumb: 'images/catalog/thumb/retail-02.jpg' },
  { cat: 'retail',          name: 'Торговый стол лофт',                                       img: 'images/catalog/retail-03.jpg',      thumb: 'images/catalog/thumb/retail-03.jpg' },
  { cat: 'retail',          name: 'Обувные стеллажи пристенные',                              img: 'images/catalog/retail-04.jpg',      thumb: 'images/catalog/thumb/retail-04.jpg' },
  { cat: 'retail',          name: 'Торговая стена для обуви',                                 img: 'images/catalog/retail-05.jpg',      thumb: 'images/catalog/thumb/retail-05.jpg' },
  { cat: 'retail',          name: 'Островная витрина с зеркалом',                             img: 'images/catalog/retail-06.jpg',      thumb: 'images/catalog/thumb/retail-06.jpg' },
  { cat: 'retail',          name: 'Стойка-вешало с подиумом',                                 img: 'images/catalog/retail-07.jpg',      thumb: 'images/catalog/thumb/retail-07.jpg' },
  { cat: 'retail',          name: 'Стеллаж-лесенка для обуви',                                img: 'images/catalog/retail-08.jpg',      thumb: 'images/catalog/thumb/retail-08.jpg' },
  { cat: 'retail',          name: 'Торговый зал обувного салона',                             img: 'images/catalog/retail-09.jpg',      thumb: 'images/catalog/thumb/retail-09.jpg' },
  { cat: 'retail',          name: 'Пристенные стеллажи и вешала',                             img: 'images/catalog/retail-10.jpg',      thumb: 'images/catalog/thumb/retail-10.jpg' },
  { cat: 'retail',          name: 'Стеллаж с рейками',                                        img: 'images/catalog/retail-11.jpg',      thumb: 'images/catalog/thumb/retail-11.jpg' },
  { cat: 'retail',          name: 'Островные подиумы для обуви',                              img: 'images/catalog/retail-12.jpg',      thumb: 'images/catalog/thumb/retail-12.jpg' },
  { cat: 'retail',          name: 'Торговые островки на подиуме',                             img: 'images/catalog/retail-13.jpg',      thumb: 'images/catalog/thumb/retail-13.jpg' },
  { cat: 'retail',          name: 'Оборудование обувного салона',                             img: 'images/catalog/retail-14.jpg',      thumb: 'images/catalog/thumb/retail-14.jpg' },
  { cat: 'retail',          name: 'Стеллаж для магазина товаров для здоровья',                img: 'images/catalog/retail-15.jpg',      thumb: 'images/catalog/thumb/retail-15.jpg' },
  { cat: 'retail',          name: 'Пристенный стеллаж с подсветкой',                          img: 'images/catalog/retail-16.jpg',      thumb: 'images/catalog/thumb/retail-16.jpg' },
  { cat: 'retail',          name: 'Стеллаж-витрина для техники',                              img: 'images/catalog/retail-17.jpg',      thumb: 'images/catalog/thumb/retail-17.jpg' },
  { cat: 'retail',          name: 'Стеллаж для аудиотехники',                                 img: 'images/catalog/retail-18.jpg',      thumb: 'images/catalog/thumb/retail-18.jpg' },
  { cat: 'retail',          name: 'Витрина-стеллаж на металлокаркасе',                        img: 'images/catalog/retail-19.jpg',      thumb: 'images/catalog/thumb/retail-19.jpg' },
  { cat: 'retail',          name: 'Пристенные стеллажи магазина',                             img: 'images/catalog/retail-20.jpg',      thumb: 'images/catalog/thumb/retail-20.jpg' },
  { cat: 'retail',          name: 'Торговое оборудование с рабочей зоной',                    img: 'images/catalog/retail-21.jpg',      thumb: 'images/catalog/thumb/retail-21.jpg' },
  { cat: 'retail',          name: 'Стеллаж с ячейками',                                       img: 'images/catalog/retail-22.jpg',      thumb: 'images/catalog/thumb/retail-22.jpg' },
  { cat: 'retail',          name: 'Стеллаж для техники',                                      img: 'images/catalog/retail-23.jpg',      thumb: 'images/catalog/thumb/retail-23.jpg' },
  { cat: 'retail',          name: 'Торговые столы для одежды',                                img: 'images/catalog/retail-24.jpg',      thumb: 'images/catalog/thumb/retail-24.jpg' },
  { cat: 'retail',          name: 'Островные столы магазина одежды',                          img: 'images/catalog/retail-25.jpg',      thumb: 'images/catalog/thumb/retail-25.jpg' },
  { cat: 'retail',          name: 'Пристенные стеллажи торгового зала',                       img: 'images/catalog/retail-26.jpg',      thumb: 'images/catalog/thumb/retail-26.jpg' },
  { cat: 'retail',          name: 'Стеллажи по периметру зала',                               img: 'images/catalog/retail-27.jpg',      thumb: 'images/catalog/thumb/retail-27.jpg' },
  { cat: 'retail',          name: 'Торговый зал салона отделки',                              img: 'images/catalog/retail-28.jpg',      thumb: 'images/catalog/thumb/retail-28.jpg' },
  { cat: 'retail',          name: 'Островной стол-витрина',                                   img: 'images/catalog/retail-29.jpg',      thumb: 'images/catalog/thumb/retail-29.jpg' },
  { cat: 'retail',          name: 'Витрина с открытыми полками',                              img: 'images/catalog/retail-30.jpg',      thumb: 'images/catalog/thumb/retail-30.jpg' },
  { cat: 'retail',          name: 'Стол-витрина с ящиками',                                   img: 'images/catalog/retail-31.jpg',      thumb: 'images/catalog/thumb/retail-31.jpg' },
  { cat: 'retail',          name: 'Торговая стойка с выдвижными ящиками',                     img: 'images/catalog/retail-32.jpg',      thumb: 'images/catalog/thumb/retail-32.jpg' },
  { cat: 'retail',          name: 'Комод-витрина с сетчатыми панелями',                       img: 'images/catalog/retail-33.jpg',      thumb: 'images/catalog/thumb/retail-33.jpg' },
  { cat: 'retail',          name: 'Торговая стойка с навесными полками',                      img: 'images/catalog/retail-34.jpg',      thumb: 'images/catalog/thumb/retail-34.jpg' },
  { cat: 'retail',          name: 'Оборудование салона отделочных материалов',                img: 'images/catalog/retail-35.jpg',      thumb: 'images/catalog/thumb/retail-35.jpg' },
  { cat: 'retail',          name: 'Входная группа и стойки салона',                           img: 'images/catalog/retail-36.jpg',      thumb: 'images/catalog/thumb/retail-36.jpg' },
  { cat: 'retail',          name: 'Торговый островок кофейни',                                img: 'images/catalog/retail-37.jpg',      thumb: 'images/catalog/thumb/retail-37.jpg' },
  { cat: 'retail',          name: 'Торговый островок фастфуда',                               img: 'images/catalog/retail-38.jpg',      thumb: 'images/catalog/thumb/retail-38.jpg' },
  { cat: 'retail',          name: 'Витрина для обуви с подсветкой',                           img: 'images/catalog/retail-39.jpg',      thumb: 'images/catalog/thumb/retail-39.jpg' },
  { cat: 'retail',          name: 'Торговый островок с сетчатыми панелями',                   img: 'images/catalog/retail-40.jpg',      thumb: 'images/catalog/thumb/retail-40.jpg' },
  { cat: 'retail',          name: 'Островок в торговом центре',                               img: 'images/catalog/retail-41.jpg',      thumb: 'images/catalog/thumb/retail-41.jpg' },
  { cat: 'retail',          name: 'Торговый островок с полками',                              img: 'images/catalog/retail-42.jpg',      thumb: 'images/catalog/thumb/retail-42.jpg' },
  { cat: 'retail',          name: 'Стеллажи торгового островка',                              img: 'images/catalog/retail-43.jpg',      thumb: 'images/catalog/thumb/retail-43.jpg' },
  { cat: 'retail',          name: 'Островок-домик для детского магазина',                     img: 'images/catalog/retail-44.jpg',      thumb: 'images/catalog/thumb/retail-44.jpg' },
  { cat: 'retail',          name: 'Торговый островок в виде домика',                          img: 'images/catalog/retail-45.jpg',      thumb: 'images/catalog/thumb/retail-45.jpg' },
  { cat: 'retail',          name: 'Детский торговый островок',                                img: 'images/catalog/retail-46.jpg',      thumb: 'images/catalog/thumb/retail-46.jpg' },
  { cat: 'retail',          name: 'Вешала для магазина одежды',                               img: 'images/catalog/retail-47.jpg',      thumb: 'images/catalog/thumb/retail-47.jpg' },
  { cat: 'retail',          name: 'Стеллаж для головных уборов',                              img: 'images/catalog/retail-48.jpg',      thumb: 'images/catalog/thumb/retail-48.jpg' },
  { cat: 'retail',          name: 'Вешало с верхней полкой',                                  img: 'images/catalog/retail-49.jpg',      thumb: 'images/catalog/thumb/retail-49.jpg' },
  { cat: 'retail',          name: 'Каркасные вешала с полками',                               img: 'images/catalog/retail-50.jpg',      thumb: 'images/catalog/thumb/retail-50.jpg' },
  { cat: 'retail',          name: 'Торговое оборудование для одежды',                         img: 'images/catalog/retail-51.jpg',      thumb: 'images/catalog/thumb/retail-51.jpg' },

  // Мебель для учебных заведений — партия 3
  { cat: 'education',       name: 'Учебный стол на металлокаркасе',                           img: 'images/catalog/education-01.jpg',      thumb: 'images/catalog/thumb/education-01.jpg' },
  { cat: 'education',       name: 'Столы компьютерного класса',                               img: 'images/catalog/education-02.jpg',      thumb: 'images/catalog/thumb/education-02.jpg' },
  { cat: 'education',       name: 'Рабочие места компьютерного класса',                       img: 'images/catalog/education-03.jpg',      thumb: 'images/catalog/thumb/education-03.jpg' },
  { cat: 'education',       name: 'Компьютерные столы в ряд',                                 img: 'images/catalog/education-04.jpg',      thumb: 'images/catalog/thumb/education-04.jpg' },
  { cat: 'education',       name: 'Учебное место с металлокаркасом',                          img: 'images/catalog/education-05.jpg',      thumb: 'images/catalog/thumb/education-05.jpg' },
  { cat: 'education',       name: 'Стол для аудитории',                                       img: 'images/catalog/education-06.jpg',      thumb: 'images/catalog/thumb/education-06.jpg' },
  { cat: 'education',       name: 'Стеллаж с ячейками и тумбами',                             img: 'images/catalog/education-07.jpg',      thumb: 'images/catalog/thumb/education-07.jpg' },
  { cat: 'education',       name: 'Стеллаж для учебных пособий',                              img: 'images/catalog/education-08.jpg',      thumb: 'images/catalog/thumb/education-08.jpg' },
  { cat: 'education',       name: 'Переговорный стол для аудитории',                          img: 'images/catalog/education-09.jpg',      thumb: 'images/catalog/thumb/education-09.jpg' },
  { cat: 'education',       name: 'Тумба под телевизор для аудитории',                        img: 'images/catalog/education-10.jpg',      thumb: 'images/catalog/thumb/education-10.jpg' },
  { cat: 'education',       name: 'Стол для семинаров',                                       img: 'images/catalog/education-11.jpg',      thumb: 'images/catalog/thumb/education-11.jpg' },
  { cat: 'education',       name: 'Тумба с распашными дверями',                               img: 'images/catalog/education-12.jpg',      thumb: 'images/catalog/thumb/education-12.jpg' },

  // Кухни встроенные — партия 3
  { cat: 'kitchens',        name: 'Кухня с деревянной столешницей',                           img: 'images/catalog/kitchens-01.jpg',      thumb: 'images/catalog/thumb/kitchens-01.jpg' },
  { cat: 'kitchens',        name: 'Кухонная зона с мойкой',                                   img: 'images/catalog/kitchens-02.jpg',      thumb: 'images/catalog/thumb/kitchens-02.jpg' },
  { cat: 'kitchens',        name: 'Встроенная кухня с ящиками',                               img: 'images/catalog/kitchens-03.jpg',      thumb: 'images/catalog/thumb/kitchens-03.jpg' },
  { cat: 'kitchens',        name: 'Столешница из массива',                                    img: 'images/catalog/kitchens-04.jpg',      thumb: 'images/catalog/thumb/kitchens-04.jpg' },
  { cat: 'kitchens',        name: 'Кухня с варочной панелью',                                 img: 'images/catalog/kitchens-05.jpg',      thumb: 'images/catalog/thumb/kitchens-05.jpg' },
  { cat: 'kitchens',        name: 'Кухня-ниша с открытой полкой',                             img: 'images/catalog/kitchens-06.jpg',      thumb: 'images/catalog/thumb/kitchens-06.jpg' },
  { cat: 'kitchens',        name: 'Кухонный блок с вытяжкой',                                 img: 'images/catalog/kitchens-07.jpg',      thumb: 'images/catalog/thumb/kitchens-07.jpg' },
  { cat: 'kitchens',        name: 'Кухонный модуль с нижней полкой',                          img: 'images/catalog/kitchens-08.jpg',      thumb: 'images/catalog/thumb/kitchens-08.jpg' },
  { cat: 'kitchens',        name: 'Кухонный остров из массива',                               img: 'images/catalog/kitchens-09.jpg',      thumb: 'images/catalog/thumb/kitchens-09.jpg' },
  { cat: 'kitchens',        name: 'Кухонный модуль для бани',                                 img: 'images/catalog/kitchens-10.jpg',      thumb: 'images/catalog/thumb/kitchens-10.jpg' },
  { cat: 'kitchens',        name: 'Кухня-бар с медным фартуком',                              img: 'images/catalog/kitchens-11.jpg',      thumb: 'images/catalog/thumb/kitchens-11.jpg' },
  { cat: 'kitchens',        name: 'Кухонный блок с навесными полками',                        img: 'images/catalog/kitchens-12.jpg',      thumb: 'images/catalog/thumb/kitchens-12.jpg' },

  // Тумбы под раковину и стиральную машину — партия 3
  { cat: 'bathroom',        name: 'Тумба под две раковины',                                   img: 'images/catalog/bathroom-01.jpg',      thumb: 'images/catalog/thumb/bathroom-01.jpg' },
  { cat: 'bathroom',        name: 'Тумба с полкой для полотенец',                             img: 'images/catalog/bathroom-02.jpg',      thumb: 'images/catalog/thumb/bathroom-02.jpg' },
  { cat: 'bathroom',        name: 'Столешница из массива под раковины',                       img: 'images/catalog/bathroom-03.jpg',      thumb: 'images/catalog/thumb/bathroom-03.jpg' },
  { cat: 'bathroom',        name: 'Тумба в санузел на металлокаркасе',                        img: 'images/catalog/bathroom-04.jpg',      thumb: 'images/catalog/thumb/bathroom-04.jpg' },
  { cat: 'bathroom',        name: 'Двойная раковина на деревянной столешнице',                img: 'images/catalog/bathroom-05.jpg',      thumb: 'images/catalog/thumb/bathroom-05.jpg' },
  { cat: 'bathroom',        name: 'Тумба под раковину в санузел',                             img: 'images/catalog/bathroom-06.jpg',      thumb: 'images/catalog/thumb/bathroom-06.jpg' },
  { cat: 'bathroom',        name: 'Тумба с распашными дверями под раковину',                  img: 'images/catalog/bathroom-07.jpg',      thumb: 'images/catalog/thumb/bathroom-07.jpg' },
  { cat: 'bathroom',        name: 'Консоль под раковину',                                     img: 'images/catalog/bathroom-08.jpg',      thumb: 'images/catalog/thumb/bathroom-08.jpg' },
  { cat: 'bathroom',        name: 'Тумба под раковину из массива',                            img: 'images/catalog/bathroom-09.jpg',      thumb: 'images/catalog/thumb/bathroom-09.jpg' },
  { cat: 'bathroom',        name: 'Рифлёная тумба под две раковины',                          img: 'images/catalog/bathroom-10.jpg',      thumb: 'images/catalog/thumb/bathroom-10.jpg' },

  // Прихожие лофт — партия 3
  { cat: 'hallway',         name: 'Прихожая-стеллаж с крючками',                              img: 'images/catalog/hallway-01.jpg',      thumb: 'images/catalog/thumb/hallway-01.jpg' },
  { cat: 'hallway',         name: 'Вешалка с комодом и полкой',                               img: 'images/catalog/hallway-02.jpg',      thumb: 'images/catalog/thumb/hallway-02.jpg' },
  { cat: 'hallway',         name: 'Прихожая с открытыми полками',                             img: 'images/catalog/hallway-03.jpg',      thumb: 'images/catalog/thumb/hallway-03.jpg' },
  { cat: 'hallway',         name: 'Прихожая с зеркалом и пуфом',                              img: 'images/catalog/hallway-04.jpg',      thumb: 'images/catalog/thumb/hallway-04.jpg' },
  { cat: 'hallway',         name: 'Стеллаж прихожей с крючками',                              img: 'images/catalog/hallway-05.jpg',      thumb: 'images/catalog/thumb/hallway-05.jpg' },
  { cat: 'hallway',         name: 'Прихожая с ростовым зеркалом',                             img: 'images/catalog/hallway-06.jpg',      thumb: 'images/catalog/thumb/hallway-06.jpg' },
  { cat: 'hallway',         name: 'Зона прихожей в номере',                                   img: 'images/catalog/hallway-07.jpg',      thumb: 'images/catalog/thumb/hallway-07.jpg' },
  { cat: 'hallway',         name: 'Прихожая с пуфом',                                         img: 'images/catalog/hallway-08.jpg',      thumb: 'images/catalog/thumb/hallway-08.jpg' },
  { cat: 'hallway',         name: 'Прихожая с ящиками',                                       img: 'images/catalog/hallway-09.jpg',      thumb: 'images/catalog/thumb/hallway-09.jpg' },
  { cat: 'hallway',         name: 'Вешалка-стеллаж с комодом',                                img: 'images/catalog/hallway-10.jpg',      thumb: 'images/catalog/thumb/hallway-10.jpg' },
  { cat: 'hallway',         name: 'Прихожая со шкафом и крючками',                            img: 'images/catalog/hallway-11.jpg',      thumb: 'images/catalog/thumb/hallway-11.jpg' },

  // Столы обеденные — партия 3
  { cat: 'dining-tables',   name: 'Обеденный стол для беседки',                               img: 'images/catalog/dining-tables-01.jpg',      thumb: 'images/catalog/thumb/dining-tables-01.jpg' },
  { cat: 'dining-tables',   name: 'Длинный обеденный стол со скамьями',                       img: 'images/catalog/dining-tables-02.jpg',      thumb: 'images/catalog/thumb/dining-tables-02.jpg' },
  { cat: 'dining-tables',   name: 'Обеденный стол из массива',                                img: 'images/catalog/dining-tables-03.jpg',      thumb: 'images/catalog/thumb/dining-tables-03.jpg' },
  { cat: 'dining-tables',   name: 'Стол со скамьями',                                         img: 'images/catalog/dining-tables-04.jpg',      thumb: 'images/catalog/thumb/dining-tables-04.jpg' },
  { cat: 'dining-tables',   name: 'Обеденный стол с угловым диваном',                         img: 'images/catalog/dining-tables-05.jpg',      thumb: 'images/catalog/thumb/dining-tables-05.jpg' },
  { cat: 'dining-tables',   name: 'Обеденная группа со стульями',                             img: 'images/catalog/dining-tables-06.jpg',      thumb: 'images/catalog/thumb/dining-tables-06.jpg' },

  // Тумбы под ТВ — партия 3
  { cat: 'tv-units',        name: 'Тумба под ТВ с винной секцией',                            img: 'images/catalog/tv-units-03.jpg',      thumb: 'images/catalog/thumb/tv-units-03.jpg' },
  { cat: 'tv-units',        name: 'Комод под телевизор',                                      img: 'images/catalog/tv-units-04.jpg',      thumb: 'images/catalog/thumb/tv-units-04.jpg' },
  { cat: 'tv-units',        name: 'ТВ-зона со стеллажом и тумбой',                            img: 'images/catalog/tv-units-05.jpg',      thumb: 'images/catalog/thumb/tv-units-05.jpg' },

  // Стеллажи — партия 3
  { cat: 'shelving',        name: 'Стеллаж с деревянными полками',                            img: 'images/catalog/shelving-04.jpg',      thumb: 'images/catalog/thumb/shelving-04.jpg' },
  { cat: 'shelving',        name: 'Стеллаж на металлокаркасе',                                img: 'images/catalog/shelving-05.jpg',      thumb: 'images/catalog/thumb/shelving-05.jpg' },
  { cat: 'shelving',        name: 'Стеллаж с дровницей',                                      img: 'images/catalog/shelving-06.jpg',      thumb: 'images/catalog/thumb/shelving-06.jpg' },
  { cat: 'shelving',        name: 'Стеллаж-дровница',                                         img: 'images/catalog/shelving-07.jpg',      thumb: 'images/catalog/thumb/shelving-07.jpg' },
  { cat: 'shelving',        name: 'Настенный стеллаж лофт',                                   img: 'images/catalog/shelving-08.jpg',      thumb: 'images/catalog/thumb/shelving-08.jpg' },

  // Мебель для глэмпинга и баз отдыха — партия 3
  { cat: 'glamping',        name: 'Интерьер номера шале',                                     img: 'images/catalog/glamping-01.jpg',      thumb: 'images/catalog/thumb/glamping-01.jpg' },
  { cat: 'glamping',        name: 'Комод с деревянной столешницей',                           img: 'images/catalog/glamping-02.jpg',      thumb: 'images/catalog/thumb/glamping-02.jpg' },
  { cat: 'glamping',        name: 'Зеркало и вешалка в номере',                               img: 'images/catalog/glamping-03.jpg',      thumb: 'images/catalog/thumb/glamping-03.jpg' },
  { cat: 'glamping',        name: 'Барная стойка номера',                                     img: 'images/catalog/glamping-04.jpg',      thumb: 'images/catalog/thumb/glamping-04.jpg' },
  { cat: 'glamping',        name: 'Столешница-барная стойка',                                 img: 'images/catalog/glamping-05.jpg',      thumb: 'images/catalog/thumb/glamping-05.jpg' },
  { cat: 'glamping',        name: 'Рабочая зона номера',                                      img: 'images/catalog/glamping-06.jpg',      thumb: 'images/catalog/thumb/glamping-06.jpg' },
  { cat: 'glamping',        name: 'Прихожая номера с зеркалом',                               img: 'images/catalog/glamping-07.jpg',      thumb: 'images/catalog/thumb/glamping-07.jpg' },
  { cat: 'glamping',        name: 'Общая зона базы отдыха',                                   img: 'images/catalog/glamping-08.jpg',      thumb: 'images/catalog/thumb/glamping-08.jpg' },
  { cat: 'glamping',        name: 'Стеллаж с корзинами',                                      img: 'images/catalog/glamping-09.jpg',      thumb: 'images/catalog/thumb/glamping-09.jpg' },
  { cat: 'glamping',        name: 'Обеденная зона номера',                                    img: 'images/catalog/glamping-10.jpg',      thumb: 'images/catalog/thumb/glamping-10.jpg' },
  { cat: 'glamping',        name: 'Гостиная зона шале',                                       img: 'images/catalog/glamping-11.jpg',      thumb: 'images/catalog/thumb/glamping-11.jpg' },
  { cat: 'glamping',        name: 'Номер с диваном и консолью',                               img: 'images/catalog/glamping-12.jpg',      thumb: 'images/catalog/thumb/glamping-12.jpg' },
  { cat: 'glamping',        name: 'Гостиная номера шале',                                     img: 'images/catalog/glamping-13.jpg',      thumb: 'images/catalog/thumb/glamping-13.jpg' },
  { cat: 'glamping',        name: 'Барный стол с нишей',                                      img: 'images/catalog/glamping-14.jpg',      thumb: 'images/catalog/thumb/glamping-14.jpg' },
  { cat: 'glamping',        name: 'Зона отдыха в номере',                                     img: 'images/catalog/glamping-15.jpg',      thumb: 'images/catalog/thumb/glamping-15.jpg' },
  { cat: 'glamping',        name: 'Спальня с прихожей-стеллажом',                             img: 'images/catalog/glamping-16.jpg',      thumb: 'images/catalog/thumb/glamping-16.jpg' },
  { cat: 'glamping',        name: 'Обеденная зона бани',                                      img: 'images/catalog/glamping-17.jpg',      thumb: 'images/catalog/thumb/glamping-17.jpg' },
  { cat: 'glamping',        name: 'Кухонный шкаф для дома отдыха',                            img: 'images/catalog/glamping-18.jpg',      thumb: 'images/catalog/thumb/glamping-18.jpg' },
  { cat: 'glamping',        name: 'Угловой диван для зоны отдыха',                            img: 'images/catalog/glamping-19.jpg',      thumb: 'images/catalog/thumb/glamping-19.jpg' },
  { cat: 'glamping',        name: 'Лаунж-зона дома отдыха',                                   img: 'images/catalog/glamping-20.jpg',      thumb: 'images/catalog/thumb/glamping-20.jpg' },
  { cat: 'glamping',        name: 'Обеденная зона с угловым диваном',                         img: 'images/catalog/glamping-21.jpg',      thumb: 'images/catalog/thumb/glamping-21.jpg' },
  { cat: 'glamping',        name: 'Угловой диван с полосатой обивкой',                        img: 'images/catalog/glamping-22.jpg',      thumb: 'images/catalog/thumb/glamping-22.jpg' },
  { cat: 'glamping',        name: 'Зона отдыха с угловым диваном',                            img: 'images/catalog/glamping-23.jpg',      thumb: 'images/catalog/thumb/glamping-23.jpg' },

  // Уличная мебель — партия 3
  { cat: 'outdoor',         name: 'Лаунж-комплект для беседки',                               img: 'images/catalog/outdoor-40.jpg',      thumb: 'images/catalog/thumb/outdoor-40.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван со столом на террасе',                       img: 'images/catalog/outdoor-41.jpg',      thumb: 'images/catalog/thumb/outdoor-41.jpg' },
  { cat: 'outdoor',         name: 'Обеденная группа под навесом',                             img: 'images/catalog/outdoor-42.jpg',      thumb: 'images/catalog/thumb/outdoor-42.jpg' },
  { cat: 'outdoor',         name: 'Длинный диван со столом',                                  img: 'images/catalog/outdoor-43.jpg',      thumb: 'images/catalog/thumb/outdoor-43.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван с журнальным столом',                        img: 'images/catalog/outdoor-44.jpg',      thumb: 'images/catalog/thumb/outdoor-44.jpg' },
  { cat: 'outdoor',         name: 'Лаунж-зона в беседке',                                     img: 'images/catalog/outdoor-45.jpg',      thumb: 'images/catalog/thumb/outdoor-45.jpg' },
  { cat: 'outdoor',         name: 'Комплект с креслами на террасе',                           img: 'images/catalog/outdoor-46.jpg',      thumb: 'images/catalog/thumb/outdoor-46.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван у зелёной стены',                            img: 'images/catalog/outdoor-47.jpg',      thumb: 'images/catalog/thumb/outdoor-47.jpg' },
  { cat: 'outdoor',         name: 'Лаунж-комплект у бассейна',                                img: 'images/catalog/outdoor-48.jpg',      thumb: 'images/catalog/thumb/outdoor-48.jpg' },
  { cat: 'outdoor',         name: 'Модульный комплект у бассейна',                            img: 'images/catalog/outdoor-49.jpg',      thumb: 'images/catalog/thumb/outdoor-49.jpg' },
  { cat: 'outdoor',         name: 'Обеденная группа в беседке',                               img: 'images/catalog/outdoor-50.jpg',      thumb: 'images/catalog/thumb/outdoor-50.jpg' },
  { cat: 'outdoor',         name: 'Комплект с креслами и столом',                             img: 'images/catalog/outdoor-51.jpg',      thumb: 'images/catalog/thumb/outdoor-51.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван на террасе',                                 img: 'images/catalog/outdoor-52.jpg',      thumb: 'images/catalog/thumb/outdoor-52.jpg' },
  { cat: 'outdoor',         name: 'Диван с деревянными подлокотниками',                       img: 'images/catalog/outdoor-53.jpg',      thumb: 'images/catalog/thumb/outdoor-53.jpg' },
  { cat: 'outdoor',         name: 'Садовый диван со светлыми подушками',                      img: 'images/catalog/outdoor-54.jpg',      thumb: 'images/catalog/thumb/outdoor-54.jpg' },
  { cat: 'outdoor',         name: 'Лаунж-зона у барбекю',                                     img: 'images/catalog/outdoor-55.jpg',      thumb: 'images/catalog/thumb/outdoor-55.jpg' },
  { cat: 'outdoor',         name: 'Комплект мебели для настила',                              img: 'images/catalog/outdoor-56.jpg',      thumb: 'images/catalog/thumb/outdoor-56.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван с обеденным столом',                         img: 'images/catalog/outdoor-57.jpg',      thumb: 'images/catalog/thumb/outdoor-57.jpg' },
  { cat: 'outdoor',         name: 'Лаунж-зона остеклённой террасы',                           img: 'images/catalog/outdoor-58.jpg',      thumb: 'images/catalog/thumb/outdoor-58.jpg' },
  { cat: 'outdoor',         name: 'Обеденная группа с креслами',                              img: 'images/catalog/outdoor-59.jpg',      thumb: 'images/catalog/thumb/outdoor-59.jpg' },
  { cat: 'outdoor',         name: 'Светлый лаунж-комплект',                                   img: 'images/catalog/outdoor-60.jpg',      thumb: 'images/catalog/thumb/outdoor-60.jpg' },
  { cat: 'outdoor',         name: 'Длинный диван с обеденным столом',                         img: 'images/catalog/outdoor-61.jpg',      thumb: 'images/catalog/thumb/outdoor-61.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван в перголе',                                  img: 'images/catalog/outdoor-62.jpg',      thumb: 'images/catalog/thumb/outdoor-62.jpg' },
  { cat: 'outdoor',         name: 'Комплект с креслами на балконе',                           img: 'images/catalog/outdoor-63.jpg',      thumb: 'images/catalog/thumb/outdoor-63.jpg' },
  { cat: 'outdoor',         name: 'Угловой диван со столиком',                                img: 'images/catalog/outdoor-64.jpg',      thumb: 'images/catalog/thumb/outdoor-64.jpg' },

  // Мебель для офиса — партия 3
  { cat: 'office',          name: 'Рабочее место с угловым столом',                           img: 'images/catalog/office-42.jpg',      thumb: 'images/catalog/thumb/office-42.jpg' },
];

/* Пока позиций нет — показываем по столько заглушек на категорию,
   чтобы каркас каталога был виден. Поставить 0, когда наполнится. */
const CATALOG_PLACEHOLDERS_PER_CATEGORY = 3;
